10.times do
  10.times do
    with_fx :pan do
      with_fx :echo do
        with_fx :reverb do
          with_fx :echo do
            with_fx :reverb do
              with_fx :echo do
                with_fx :reverb do
                  with_fx :echo do
                    with_fx :reverb do
                      with_fx :echo do
                        with_fx :reverb do
                          play sample :ambi_choir
                          use_synth :piano
                          use_synth :pretty_bell
                          use_bpm rrand(0,1000)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                        end
                      end
                      with_fx :echo do
                        with_fx :reverb do
                          play sample :drum_cowbell
                          use_synth :pretty_bell
                          use_synth :piano
                          use_bpm rrand(0,1000)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                        end
                      end
                      with_fx :echo do
                        with_fx :reverb do
                          play sample :elec_bong
                          use_synth :piano
                          use_synth :pretty_bell
                          use_bpm rrand(0,1000)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                        end
                      end
                      with_fx :echo do
                        with_fx :reverb do
                          play sample :elec_triangle
                          use_synth :pretty_bell
                          use_synth :piano
                          use_bpm rrand(0,1000)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                        end
                      end
                      with_fx :echo do
                        with_fx :reverb do
                          play sample :elec_wood
                          use_synth :piano
                          use_synth :pretty_bell
                          use_bpm rrand(0,1000)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                        end
                      end
                      with_fx :echo do
                        with_fx :reverb do
                          play sample :loop_tabla
                          use_synth :pretty_bell
                          use_synth :piano
                          use_bpm rrand(0,1000)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([60,66])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([61,65,67])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([62,68])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,1000)
                          play_chord([63,69,71])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                          use_bpm rrand(0,500)
                          play_chord([64,70])
                          play rrand(48,83)
                          play rrand(0,231)
                          sleep rrand(0,1)
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
end
