in_thread do
  with_fx :echo do
    with_fx :reverb do
      with_fx :echo do
        with_fx :reverb do
          2013.times do
            sample :begining_of_earthquake
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :C4
            sleep rrand(0,1)
            sample :eaten_by_a_monster1
            sleep rrand(0,1)
            sample :chordeb4
            sleep rrand(0,1)
            sample :ghosts
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :indoperc1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Fs4
            sleep rrand(0,1)
            sample :monster_grief
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :rain
            sleep rrand(0,1)
            sample :chordd4
            sleep rrand(0,1)
            sample :storm_land
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :thunder
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Ab4
            sleep rrand(0,1)
            sample :umbrella1_C
            sleep rrand(0,1)
            sample :clusterSHIbs
            sleep rrand(0,1)
            sample :walking1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :D4
            sleep rrand(0,1)
            sample :zombie_eating1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :Budda_large_bell
            sleep rrand(0,1)
            sample :chord3
            sleep rrand(0,1)
            sample :Japanese_drum1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :ah
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Eb4
            sleep rrand(0,1)
            sample :breaking_a_cup
            sleep rrand(0,1)
            sample :chorde4
            sleep rrand(0,1)
            sample :coins
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :dark_atmosphere
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :B4
            sleep rrand(0,1)
            sample :eaten_by_a_monster2
            sleep rrand(0,1)
            sample :clusterSHAnor
            sleep rrand(0,1)
            sample :falling_down
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Bb4
            sleep rrand(0,1)
            sample :ghost_sigh
            sleep rrand(0,1)
            sample :chordcs4
            sleep rrand(0,1)
            sample :haevy_rain_loop
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :indoperc2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :E4
            sleep rrand(0,1)
            sample :knocking_a_wooden_door1
            sleep rrand(0,1)
            sample :chordf4
            sleep rrand(0,1)
            sample :lunch_of_a_monster1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :monster_heartbeats1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :F4
            sleep rrand(0,1)
            sample :oshiire
            sleep rrand(0,1)
            sample :clusterJRFall
            sleep rrand(0,1)
            sample :rain_thunder1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :B4
            sleep rrand(0,1)
            sample :satan_voice
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :thunder1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :A4
            sleep rrand(0,1)
            sample :umbrella1_O
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :walking_at_night
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Eb4
            sleep rrand(0,1)
            sample :zombie_eating2
            sleep rrand(0,1)
            sample :chordeb4
            sleep rrand(0,1)
            sample :Buddhism_sutra1
            sleep rrand(0,1)
            sample :clusterJRFall
            sleep rrand(0,1)
            sample :Japanese_drum2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :ambi_choir
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Fs4
            sleep rrand(0,1)
            sample :death_sound1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :F4
            sleep rrand(0,1)
            sample :ghostbreath1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :hell_bell
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :knocking_a_wooden_door2
            sleep rrand(0,1)
            sample :chordd4
            sleep rrand(0,1)
            sample :lunch_of_a_monster2
            sleep rrand(0,1)
            sample :chordf4
            sleep rrand(0,1)
            sample :monster_heartbeats2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :E4
            sleep rrand(0,1)
            sample :rain_thunder2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :strong_wind1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Ab4
            sleep rrand(0,1)
            sample :terror
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :umbrella2_C
            sleep rrand(0,1)
            sample :chordcs4
            sleep rrand(0,1)
            sample :Budda_small_bell
            sleep rrand(0,1)
            sample :clusterSHIbs
            sleep rrand(0,1)
            sample :Buddhism_sutra2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :D4
            sleep rrand(0,1)
            sample :ambi_dark_woosh
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Bb4
            sleep rrand(0,1)
            sample :coming_of_terror
            sleep rrand(0,1)
            sample :chordcs4
            sleep rrand(0,1)
            sample :death_sound2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :footsteps_of_a_giant
            sleep rrand(0,1)
            sample :chord3
            sleep rrand(0,1)
            sample :ghostbreath2
            sleep rrand(0,1)
            sample :clusterSHAnor
            sleep rrand(0,1)
            sample :heartbeat1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :B4
            sleep rrand(0,1)
            sample :korantalk2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :lunch_of_a_monster3
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Eb4
            sleep rrand(0,1)
            sample :monster_heartbeats3
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :roar1
            sleep rrand(0,1)
            sample :chorde4
            sleep rrand(0,1)
            sample :strong_wind2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :D4
            sleep rrand(0,1)
            sample :terror_attack
            sleep rrand(0,1)
            sample :chordf4
            sleep rrand(0,1)
            sample :umbrella2_O
            sleep rrand(0,1)
            sample :clusterSHIbs
            sleep rrand(0,1)
            sample :ambi_drone
            sleep rrand(0,1)
            sample :chordcs4
            sleep rrand(0,1)
            sample :death_sound3
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Bb4
            sleep rrand(0,1)
            sample :fusuma
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Gs
            sleep rrand(0,1)
            sample :ghostlaugh
            sleep rrand(0,1)
            sample :clusterSHAnor
            sleep rrand(0,1)
            sample :hell_fire
            sleep rrand(0,1)
            sample :chord3
            sleep rrand(0,1)
            sample :koreancymb
            sleep rrand(0,1)
            sample :chordcs4
            sleep rrand(0,1)
            sample :lunch_of_a_monster4
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Cs4
            sleep rrand(0,1)
            sample :monster_roaning1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :F4
            sleep rrand(0,1)
            sample :roar2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :G4
            sleep rrand(0,1)
            sample :storm_and_window1
            sleep rrand(0,1)
            sample :clusterJRFall
            sleep rrand(0,1)
            sample :terror_clock
            sleep rrand(0,1)
            sample :chordeb4
            sleep rrand(0,1)
            sample :umbrella_rain1
            sleep rrand(0,1)
            sample :chordcs4
            sleep rrand(0,1)
            sample :ambi_glass_hum
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :F4
            sleep rrand(0,1)
            sample :death_sound4
            sleep rrand(0,1)
            sample :clusterSHAnor
            sleep rrand(0,1)
            sample :ghosts
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :heartbeats
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(48,83)
            sleep rrand(0,1)
            sample :koreantalk1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,24)
            sleep rrand(0,1)
            sample :loop_tabla
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(207,231)
            sleep rrand(0,1)
            sample :monster_roaning2
            sleep rrand(0,1)
            sample :clusterJRFall
            sleep rrand(0,1)
            sample :roar3
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Cs4
            sleep rrand(0,1)
            sample :storm_and_window2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :F4
            sleep rrand(0,1)
            sample :umbrella_rain2
            sleep rrand(0,1)
            sample :clusterSHAnor
            sleep rrand(0,1)
            sample :ambi_glass_rub
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(207,231)
            sleep rrand(0,1)
            sample :devil_groaning1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(48,83)
            sleep rrand(0,1)
            sample :going_mad1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,231)
            sleep rrand(0,1)
            sample :hell_gear
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(0,24)
            sleep rrand(0,1)
            sample :monster_roaning3
            sleep rrand(0,1)
            sample :chord3
            sleep rrand(0,1)
            sample :storm_and_window3
            sleep rrand(0,1)
            sample :chordeb4
            sleep rrand(0,1)
            sample :umbrella_rain2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :F4
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(24,48)
            sleep rrand(0,1)
            sample :ambi_haunted_hum
            sleep rrand(0,1)
            sample :clusterJRFall
            sleep rrand(0,1)
            sample :devil_groaning2
            sleep rrand(0,1)
            sample :chordeb4
            sleep rrand(0,1)
            sample :going_mad2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :A4
            sleep rrand(0,1)
          end
        end
      end
    end
  end
end
in_thread do
  with_fx :echo do
    with_fx :reverb do
      with_fx :echo do
        with_fx :reverb do
          2013.times do
            sample :horror_piano_chord1
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :B4
            sleep rrand(0,1)
            sample :monstersnore1
            sleep rrand(0,1)
            sample :chord3
            sleep rrand(0,1)
            sample :storm_and_window4
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(183,207)
            sleep rrand(0,1)
            sample :umbrella_raindrops
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(48,72)
            sleep rrand(0,1)
            sample :ambi_lunar_land
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(24,48)
            sleep rrand(0,1)
            sample :devil_groaning3
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(72,96)
            sleep rrand(0,1)
            sample :horror_piano_chord2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :F4
            sleep rrand(0,1)
            sample :monstersnore2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Cs4
            sleep rrand(0,1)
            sample :storm_and_window5
            sleep rrand(0,1)
            sample :chordd4
            sleep rrand(0,1)
            sample :devil_laughing1
            sleep rrand(0,1)
            sample :chord3
            sleep rrand(0,1)
            sample :horror_piano_chord3
            sleep rrand(0,1)
            sample :clusterSHAnor
            sleep rrand(0,1)
            sample :storm_and_window6
            sleep rrand(0,1)
            sample :clusterSHIbs
            sleep rrand(0,1)
            sample :devil_laughing2
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :Bb4
            sleep rrand(0,1)
            sample :horror_piano_chord4
            sleep rrand(0,1)
            use_synth :pretty_bell
            play :E4
            sleep rrand(0,1)
            sample :storm_coming1
            sleep rrand(0,1)
            sample :chordcs4
            sleep rrand(0,1)
            sample :devil_laughing3
            sleep rrand(0,1)
            use_synth :pretty_bell
            play rrand(48,72)
            sleep rrand(0,1)
            sample :horror_zone1
            sleep rrand(0,1)
          end
        end
      end
    end
  end
end
